### ISSUE TITLE
Error when used with scalaz-core 7.2.0

### ISSUE THREAD

**Issue by monkeygroover** [typelevel/scalaz-scalatest#6]
Probably not surprising as 7.2.0. is probably not binary compatible? but I didn't know where the best place to discuss this was. When used with scalaz-core 7.2.0 I got the following error when trying to use haveFailure to check a `ValidationNel[String, Int]` (fine with 7.1.4)

simple repro:

` "test".failureNel should haveFailure("test")`

stack trace:

`[info] Exception encountered when attempting to run a suite with class name: CheckoutSpec *** ABORTED ***
[info]   java.lang.NoSuchMethodError: scalaz.NonEmptyList.list()Lscala/collection/immutable/List;
[info]   at org.typelevel.scalatest.ValidationMatchers$HasScalazFailureNelMatcher.apply(ValidationMatchers.scala:60)
[info]   at org.typelevel.scalatest.ValidationMatchers$HasScalazFailureNelMatcher.apply(ValidationMatchers.scala:53)
[info]   at org.scalatest.MatchersHelper$.andMatchersAndApply(MatchersHelper.scala:165)
[info]   at org.scalatest.matchers.Matcher$$anon$2.apply(Matcher.scala:568)
[info]   at org.scalatest.MatchersHelper$.andMatchersAndApply(MatchersHelper.scala:165)
[info]   at org.scalatest.matchers.Matcher$$anon$2.apply(Matcher.scala:568)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6230)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265)
[info]   at CheckoutSpec$$anonfun$12.apply$mcV$sp(CheckoutSpec.scala:94)
[info]   at CheckoutSpec$$anonfun$12.apply(CheckoutSpec.scala:91)
[info]   ..`

**Comment by monkeygroover** [comment]
https://github.com/monkeygroover/scalaz-scalatest/commit/8ecb8c4e8fbfb4b9f3974f91caec8512037d5163

**Comment by coltfred** [comment]
@monkeygroover I'm so sorry this has been broken for so long. I'm updating the scalaz 7.1 versions and will be publishing a scalaz 7.2 version soon I just need to get access to publish the bintray.

**Comment by coltfred** [comment]
@monkeygroover Version 1.0.0 supports scalaz 7.2.x. Sorry for the wait!

**Comment by monkeygroover** [comment]
thanks!
